PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 0
PRODUCT_VERSION_PATCH = 0

CIRCLE_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter OFFICIAL BETA ALPHA RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(LINEAGE_BUILDTYPE)),)
    CIRCLE_BUILDTYPE := UNOFFICIAL
    CIRCLE_EXTRAVERSION :=
endif

ifeq ($(CIRCLE_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        CIRCLE_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

CIRCLE_VERSION_SUFFIX := $(CIRCLE_BUILD_DATE)-$(CIRCLE_BUILDTYPE)$(CIRCLE_EXTRAVERSION)-$(CIRCLE_BUILD)

# Version
ifeq ($(PRODUCT_VERSION_PATCH),0)
    CIRCLE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_VERSION_SUFFIX)
    CIRCLE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)
else
    CIRCLE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_PATCH)-$(LINEAGE_VERSION_SUFFIX)
    CIRCLE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_PATCH)
endif

# LineageOS version properties
PRODUCT_PRODUCT_PROPERTIES += \
    ro.circle.version=$(LINEAGE_VERSION) \
    ro.circle.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.circle.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_PATCH) \
    ro.circle.releasetype=$(LINEAGE_BUILDTYPE)
