PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 0
PRODUCT_VERSION_PATCH = 0

CIRCLE_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter OFFICIAL BETA ALPHA RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(CIRCLE_BUILDTYPE)),)
    CIRCLE_BUILDTYPE := UNOFFICIAL
endif

ifeq ($(WITH_GMS),true)
    CIRCLE_EXTRAVERSION := -GAPPS
else
    CIRCLE_EXTRAVERSION := -VANILLA
endif

CIRCLE_VERSION_SUFFIX := $(CIRCLE_BUILD_DATE)-$(CIRCLE_BUILDTYPE)$(CIRCLE_EXTRAVERSION)-$(CIRCLE_BUILD)

# Version
ifeq ($(PRODUCT_VERSION_PATCH),0)
    CIRCLE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(CIRCLE_VERSION_SUFFIX)
    CIRCLE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)$(CIRCLE_EXTRAVERSION)
else
    CIRCLE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_PATCH)-$(CIRCLE_VERSION_SUFFIX)
    CIRCLE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_PATCH)$(CIRCLE_EXTRAVERSION)
endif

# LineageOS version properties
PRODUCT_PRODUCT_PROPERTIES += \
    ro.circle.version=$(LINEAGE_VERSION) \
    ro.circle.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.circle.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_PATCH) \
    ro.circle.releasetype=$(LINEAGE_BUILDTYPE)
